### ISSUE TITLE
Runtime Error for 'pts = torch.rand((10,1000,3))' case

### ISSUE THREAD

**Issue by tvpian** [dhyuan99/VecKM#1]
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[<ipython-input-6-5900e4ea5daf>](https://localhost:8080/#) in <cell line: 69>()
     67 vkm = VecKM()
     68 pts = torch.rand((10,1000,3))
---> 69 print(vkm(pts).shape) # it will be Complex(10,1000,256)
     70 pts = torch.rand((1000,3))
     71 print(vkm(pts).shape) # it will be Complex(1000, 256)

2 frames
[<ipython-input-6-5900e4ea5daf>](https://localhost:8080/#) in forward(self, pts)
     57             eB.transpose(-1,-2) @ eA                                            # Real(..., 2p, 2d)
     58         )                                                                       # Real(..., n, 2d)
---> 59         G = torch.complex(
     60             G[:,:self.d], G[:,self.d:]
     61         ) / torch.complex(

RuntimeError: The size of tensor a (256) must match the size of tensor b (1744) at non-singleton dimension 1

**Comment by dhyuan99** [comment]
Thanks for letting me know about that. I made a mistake when I write the readme file.
The readme file has been updated. You could copy and paste the new codes to try it out.

**Comment by tvpian** [comment]
Thanks for the quick fix. It is working now. Overall, outstanding work.
